# Generated by Django 4.1 on 2022-08-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0004_customerservices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=40)),
            ],
        ),
    ]
