# Generated by Django 4.1 on 2022-08-28 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0005_catagry'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catagry',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Work.catagry'),
        ),
    ]
